version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://localhost/CHAT
    volumes:
      - ./backend:/app/backend

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
