# Use an official Node.js runtime as a parent image
FROM node:20

# Set the working directory in the container
WORKDIR /

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install backend dependencies
RUN npm install

# Copy the entire backend directory to the container
COPY . ./

# Expose the port that the Express server will run on
EXPOSE 5000

# Command to start the Express server
CMD ["npm", "start"]
